package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmailFolder generated by hbm2java
 */
@Entity
@Table(name="email_folder"
    ,catalog="tareask"
)
public class EmailFolder  implements java.io.Serializable {


     private Integer id;
     private Email email;
     private String folder;
     private Set<EmailConversation> emailConversations = new HashSet<EmailConversation>(0);

    public EmailFolder() {
    }

	
    public EmailFolder(Email email, String folder) {
        this.email = email;
        this.folder = folder;
    }
    public EmailFolder(Email email, String folder, Set<EmailConversation> emailConversations) {
       this.email = email;
       this.folder = folder;
       this.emailConversations = emailConversations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false)
    public Email getEmail() {
        return this.email;
    }
    
    public void setEmail(Email email) {
        this.email = email;
    }

    
    @Column(name="folder", nullable=false, length=20)
    public String getFolder() {
        return this.folder;
    }
    
    public void setFolder(String folder) {
        this.folder = folder;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emailFolder")
    public Set<EmailConversation> getEmailConversations() {
        return this.emailConversations;
    }
    
    public void setEmailConversations(Set<EmailConversation> emailConversations) {
        this.emailConversations = emailConversations;
    }




}


