package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmailContact generated by hbm2java
 */
@Entity
@Table(name="email_contact"
    ,catalog="tareask"
)
public class EmailContact  implements java.io.Serializable {


     private Integer id;
     private Email email;
     private User user;

    public EmailContact() {
    }

    public EmailContact(Email email, User user) {
       this.email = email;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false)
    public Email getEmail() {
        return this.email;
    }
    
    public void setEmail(Email email) {
        this.email = email;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contact", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


