package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmailStatus generated by hbm2java
 */
@Entity
@Table(name="email_status"
    ,catalog="tareask"
)
public class EmailStatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Set<Email> emails = new HashSet<Email>(0);

    public EmailStatus() {
    }

	
    public EmailStatus(String status) {
        this.status = status;
    }
    public EmailStatus(String status, Set<Email> emails) {
       this.status = status;
       this.emails = emails;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emailStatus")
    public Set<Email> getEmails() {
        return this.emails;
    }
    
    public void setEmails(Set<Email> emails) {
        this.emails = emails;
    }




}


