package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmailMessage generated by hbm2java
 */
@Entity
@Table(name="email_message"
    ,catalog="tareask"
)
public class EmailMessage  implements java.io.Serializable {


     private Integer id;
     private EmailConversation emailConversation;
     private User user;
     private String subject;
     private String content;
     private Date date;
     private Set<MessageReceptor> messageReceptors = new HashSet<MessageReceptor>(0);
     private Set<EmailConversation> emailConversations = new HashSet<EmailConversation>(0);

    public EmailMessage() {
    }

	
    public EmailMessage(String subject, String content, Date date) {
        this.subject = subject;
        this.content = content;
        this.date = date;
    }
    public EmailMessage(EmailConversation emailConversation, User user, String subject, String content, Date date, Set<MessageReceptor> messageReceptors, Set<EmailConversation> emailConversations) {
       this.emailConversation = emailConversation;
       this.user = user;
       this.subject = subject;
       this.content = content;
       this.date = date;
       this.messageReceptors = messageReceptors;
       this.emailConversations = emailConversations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conversation")
    public EmailConversation getEmailConversation() {
        return this.emailConversation;
    }
    
    public void setEmailConversation(EmailConversation emailConversation) {
        this.emailConversation = emailConversation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUserSender")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="subject", nullable=false, length=50)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="content", nullable=false, length=65535)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emailMessage")
    public Set<MessageReceptor> getMessageReceptors() {
        return this.messageReceptors;
    }
    
    public void setMessageReceptors(Set<MessageReceptor> messageReceptors) {
        this.messageReceptors = messageReceptors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="emailMessage")
    public Set<EmailConversation> getEmailConversations() {
        return this.emailConversations;
    }
    
    public void setEmailConversations(Set<EmailConversation> emailConversations) {
        this.emailConversations = emailConversations;
    }




}


