package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Incidence generated by hbm2java
 */
@Entity
@Table(name="incidence"
    ,catalog="tareask"
)
public class Incidence  implements java.io.Serializable {


     private Integer id;
     private IncidenceStatus incidenceStatus;
     private Task task;
     private String title;
     private String description;
     private Date date;

    public Incidence() {
    }

    public Incidence(IncidenceStatus incidenceStatus, Task task, String title, String description, Date date) {
       this.incidenceStatus = incidenceStatus;
       this.task = task;
       this.title = title;
       this.description = description;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status", nullable=false)
    public IncidenceStatus getIncidenceStatus() {
        return this.incidenceStatus;
    }
    
    public void setIncidenceStatus(IncidenceStatus incidenceStatus) {
        this.incidenceStatus = incidenceStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="task", nullable=false)
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }

    
    @Column(name="title", nullable=false, length=50)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


