package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IncidenceStatus generated by hbm2java
 */
@Entity
@Table(name="incidence_status"
    ,catalog="tareask"
)
public class IncidenceStatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Set<Incidence> incidences = new HashSet<Incidence>(0);

    public IncidenceStatus() {
    }

	
    public IncidenceStatus(String status) {
        this.status = status;
    }
    public IncidenceStatus(String status, Set<Incidence> incidences) {
       this.status = status;
       this.incidences = incidences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="incidenceStatus")
    public Set<Incidence> getIncidences() {
        return this.incidences;
    }
    
    public void setIncidences(Set<Incidence> incidences) {
        this.incidences = incidences;
    }




}


