package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaskStatus generated by hbm2java
 */
@Entity
@Table(name="task_status"
    ,catalog="tareask"
)
public class TaskStatus  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Set<Task> tasks = new HashSet<Task>(0);

    public TaskStatus() {
    }

	
    public TaskStatus(String status) {
        this.status = status;
    }
    public TaskStatus(String status, Set<Task> tasks) {
       this.status = status;
       this.tasks = tasks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taskStatus")
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }




}


