package com.cristian.tareask.model;
// Generated 04-jul-2016 12:42:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaskPriority generated by hbm2java
 */
@Entity
@Table(name="task_priority"
    ,catalog="tareask"
)
public class TaskPriority  implements java.io.Serializable {


     private Integer id;
     private String priority;
     private Set<Task> tasks = new HashSet<Task>(0);

    public TaskPriority() {
    }

	
    public TaskPriority(String priority) {
        this.priority = priority;
    }
    public TaskPriority(String priority, Set<Task> tasks) {
       this.priority = priority;
       this.tasks = tasks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="priority", nullable=false, length=50)
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taskPriority")
    public Set<Task> getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set<Task> tasks) {
        this.tasks = tasks;
    }




}


